services:
  # Główny serwis SFR
  sfr-main:
    build: .
    container_name: sfr-main
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./recordings:/app/recordings
    environment:
      - SFR_ENV=production
      - SFR_CONFIG_DIR=/app/config
      - SFR_LOGS_DIR=/app/logs
    networks:
      - sfr-network
    restart: unless-stopped

  # Serwis HLS
  sfr-hls:
    image: nginx:alpine
    container_name: sfr-hls
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./recordings:/usr/share/nginx/html/streams
    ports:
      - "8080:80"
    networks:
      - sfr-network
    depends_on:
      - sfr-main

  # Serwis monitorowania
  sfr-monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: sfr-monitor
    volumes:
      - ./logs:/app/logs
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - SFR_METRICS_PORT=9090
    ports:
      - "9090:9090"
    networks:
      - sfr-network
    depends_on:
      - sfr-main

networks:
  sfr-network:
    name: sfr-network


