FROM python:3.11-slim

RUN pip install prometheus_client==0.19.0 fastapi==0.104.1 uvicorn==0.24.0 psutil==5.9.6

WORKDIR /app
COPY ./monitoring /app/monitoring

CMD ["python", "-m", "uvicorn", "monitoring.metrics_server:app", "--host", "0.0.0.0", "--port", "9090"]
