# Motion detection process for camera1
- filter: ["rtsp", "process://motion", "hls"]
  run:
    - shell://ffmpeg -i $1 -c:v libx264 -preset ultrafast -vf "fps=${fps},select=gt(scene\,${threshold})" -c:a aac -f hls -hls_time 4 -hls_list_size 5 -y $3

# Direct recording process
- filter: ["rtsp", "file"]
  run:
    - shell://ffmpeg -i $1 -c copy -f segment -segment_time 6 -segment_format mp4 -strftime 1 -reset_timestamps 1 $2


# Motion detection process for camera1
- filter: ["rtsp", "process://motion", "hls"]
  run:
    - shell://ffmpeg -i $1 -c:v libx264 -preset ultrafast -vf fps=$fps,select='gt(scene,$threshold)' -c:a aac -f hls -hls_time 4 -hls_list_size 5 -y $3

# Recording process for camera2
- filter: ["rtsp", "process://recorder", "file"]
  run:
    - shell://ffmpeg -i $1 -c copy -f segment -segment_time 86400 -segment_format $format -strftime 1 $3

# Motion detection with MQTT for camera3
- filter: ["rtsp", "process://motion", "mqtt", "file"]
  run:
    - shell://ffmpeg -i $1 -vf select='gt(scene,0.1)' -frame_pts 1 -vsync vfr -strftime 1 -update 1 $4
    - shell://mosquitto_pub -h $(echo $3 | cut -d'/' -f3) -t $(echo $3 | cut -d'/' -f4) -m "Motion detected"

# Compression process for camera4
- filter: ["rtsp", "process://compress", "rtmp"]
  run:
    - shell://ffmpeg -i $1 -c:v libx264 -preset veryfast -b:v $bitrate -maxrate $bitrate -bufsize $((bitrate*2)) -g 50 -c:a aac -b:a 128k -f flv $3

# Stream splitter for camera5
- filter: ["rtsp", "process://splitter", "hls"]
  run:
    - shell://ffmpeg -i $1 -filter_complex "[0:v]split=2[high][low];[high]scale=-1:1080[h];[low]scale=-1:720[l]" -map "[h]" -c:v libx264 -preset veryfast $3[0] -map "[l]" -c:v libx264 -preset veryfast $3[1]

# Recording with rotation for camera6
- filter: ["rtsp", "process://recorder", "file"]
  run:
    - shell://ffmpeg -i $1 -c copy -f segment -segment_time $rotate -segment_format mp4 -strftime 1 -reset_timestamps 1 $3