# Podstawowe przetwarzanie RTSP do HLS
-
  - "rtsp://camera1.local:554/stream1"
  - "process://motion?fps=5&threshold=0.3"
  - "hls://localhost:8080/camera1/stream.m3u8"

# Zapis do pliku MP4
-
  - "rtsp://camera2.local:554/stream2"
  - "process://recorder?format=mp4"
  - "file:///recordings/camera2_$(date +%Y%m%d).mp4"

# Detekcja ruchu i zapis zdarzeń
-
  - "rtsp://camera3.local:554/stream3"
  - "process://motion?sensitivity=high"
  - "mqtt://broker.local/events"
  - "file:///events/motion_$(timestamp).jpg"

# Stream z kompresją dla wolnego łącza
-
  - "rtsp://camera4.local:554/high_quality"
  - "process://compress?quality=medium&bitrate=1000k"
  - "rtmp://streaming.service.com/live/camera4"

# Multi-stream z jednego źródła
-
  - "rtsp://camera5.local:554/main"
  - "process://splitter"
  - ["hls://localhost:8080/camera5/high.m3u8", "hls://localhost:8080/camera5/low.m3u8"]

# Archiwizacja z rotacją plików
-
  - "rtsp://camera6.local:554/archive"
  - "process://recorder?rotate=24h"
  - "file:///archive/cam6/$(date +%Y%m%d_%H).mp4"
